CREATE TABLE IF NOT EXISTS PLAYER_INVENTORY (
    userId VARCHAR(64) NOT NULL,
    guildId VARCHAR(64) NOT NULL,
    itemId VARCHAR(128) NOT NULL,
    count INT NOT NULL,

    FOREIGN KEY (userId, guildId) REFERENCES USERS(userId, guildId),
    FOREIGN KEY (itemId) REFERENCES ITEMS(id)
);
