CREATE TABLE IF NOT EXISTS MONSTERS (
    id VARCHAR(128) NOT NULL PRIMARY KEY,
    name VARCHAR(128) NOT NULL,
    queryName VARCHAR(128) NOT NULL,
    baseGold INT NOT NULL,
    baseExp INT NOT NULL
);
